Repository apache/incubator-yunikorn-core, pull requests merged in 2019-08, with the labels that each got.

#27 Interface update and cleanup (SI pull request #2)
  go.mod
  go.sum
  pkg/cache/allocation_info.go
  pkg/cache/cluster_info.go
  pkg/examples/simple_example.go
  pkg/scheduler/drf_preemption_policy.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduling_allocation_ask.go
  pkg/scheduler/tests/scheduler_preemption_test.go
  pkg/scheduler/tests/scheduler_recovery_test.go
  pkg/scheduler/tests/scheduler_smoke_test.go
  pkg/scheduler/tests/schedulertestutils.go
  pkg/webservice/handlers.go
Labels: bug

#28 application state is accepted after scheduler recovery
  pkg/cache/partition_info.go
  pkg/scheduler/tests/scheduler_recovery_test.go
Labels: bug

#30 Placement rules for applications
  docs/design/scheduler-configuration.md
  pkg/cache/application_info.go
  pkg/cache/application_info_test.go
  pkg/cache/cachetestutils.go
  pkg/cache/cluster_info.go
  pkg/cache/partition_info.go
  pkg/cache/partition_info_test.go
  pkg/cache/queue_info.go
  pkg/common/configs/config.go
  pkg/common/configs/config_test.go
  pkg/common/configs/configvalidator.go
  pkg/common/security/acl.go
  pkg/common/security/acl_test.go
  pkg/common/security/usergroup.go
  pkg/common/security/usergroup_no_resolver.go
  pkg/common/security/usergroup_os_resolver.go
  pkg/common/security/usergroup_test.go
  pkg/common/security/usergroup_test_resolver.go
  pkg/examples/simple_example.go
  pkg/scheduler/partition_manager.go
  pkg/scheduler/placement/filter.go
  pkg/scheduler/placement/filter_test.go
  pkg/scheduler/placement/fixed_rule.go
  pkg/scheduler/placement/fixed_rule_test.go
  pkg/scheduler/placement/placement.go
  pkg/scheduler/placement/placement_test.go
  pkg/scheduler/placement/provided_rule.go
  pkg/scheduler/placement/provided_rule_test.go
  pkg/scheduler/placement/rule.go
  pkg/scheduler/placement/rule_test.go
  pkg/scheduler/placement/tag_rule.go
  pkg/scheduler/placement/tag_rule_test.go
  pkg/scheduler/placement/test_rule.go
  pkg/scheduler/placement/user_rule.go
  pkg/scheduler/placement/user_rule_test.go
  pkg/scheduler/scheduling_context.go
  pkg/scheduler/scheduling_partition.go
  pkg/scheduler/tests/mock_scheduler.go
  pkg/scheduler/tests/scheduler_recovery_test.go
  pkg/scheduler/tests/scheduler_smoke_test.go
  pkg/scheduler/tests/schedulertestutils.go
Labels: enhancement

#38 Remove strings.ReplaceAll for Go 1.11 compatibility
  pkg/scheduler/placement/rule.go
Labels: bug

#35 Placement rules for applications (part 2)
  docs/acls.md
  docs/design/scheduler-configuration.md
  docs/placement_rules.md
  pkg/cache/application_info.go
  pkg/cache/application_info_test.go
  pkg/cache/cacheevent/events.go
  pkg/cache/cluster_info.go
  pkg/cache/partition_info.go
  pkg/cache/partition_info_test.go
  pkg/cache/queue_info.go
  pkg/cache/queue_info_test.go
  pkg/common/configs/config_test.go
  pkg/scheduler/allocator.go
  pkg/scheduler/placement/placement.go
  pkg/scheduler/placement/placement_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduling_partition.go
  pkg/scheduler/scheduling_queue.go
  pkg/scheduler/scheduling_queue_test.go
  pkg/scheduler/tests/mock_scheduler.go
  pkg/scheduler/tests/scheduler_recovery_test.go
  pkg/scheduler/tests/scheduler_smoke_test.go
Labels: bug, documentation

#39 Update the environment setup document (add minikube)
  docs/images/dashboard_secret.png
  docs/images/dashboard_token_select.png
  docs/images/docker-dektop-minikube.png
  docs/images/docker-desktop.png
  docs/setup/env-setup.md
Labels: documentation

#40 ACL and Filter use user regexp when they should use group regexp
  pkg/common/security/acl.go
  pkg/scheduler/placement/filter.go
Labels: bug

#43 Makefile consistency changes:
  Makefile
Labels: build
