Repository apache/incubator-yunikorn-core, pull requests merged in 2020-03, with the labels that each got.

#88 [YUNIKORN-10] add pluggable app management design doc
  docs/design/pluggable-app-management.md
  docs/images/pluggable-app-mgmt.jpg
Labels: documentation

#94 [YUNIKORN-6] Deadlock in the scheduler when restoring a node with allocations
  pkg/cache/cachetestutils.go
  pkg/cache/initializer.go
  pkg/cache/initializer_test.go
  pkg/cache/partition_info.go
  pkg/cache/queue_info.go
  pkg/scheduler/partition_manager.go
  pkg/scheduler/preemptor.go
  pkg/scheduler/scheduling_application.go
  pkg/scheduler/scheduling_queue.go
  pkg/scheduler/scheduling_queue_test.go
  pkg/scheduler/sorters.go
  pkg/scheduler/sorters_test.go
  pkg/scheduler/tests/scheduler_recovery_test.go
  pkg/scheduler/tests/scheduler_smoke_test.go
Labels: bug

#95 [YUNIKORN-15] Fix data race in queue create
  pkg/scheduler/scheduling_queue.go
Labels: bug

#100 [YUNIKORN-5]Change the contribution guide and add .asf.yaml
  .asf.yaml
  .golangci.yml
  CLAs/Cloudera CCLA_25APR2018.pdf
  CLAs/Cloudera ICLA_25APR2018.pdf
  README.md
  docs/how-to-contribute.md
  docs/queue_config.md
  docs/reporting-issues.md
Labels: build, documentation

#107 [YUNIKORN-30] fix flaky unit test
  Makefile
  pkg/common/utils.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduling_application.go
  pkg/scheduler/scheduling_node.go
  pkg/scheduler/scheduling_partition.go
  pkg/scheduler/scheduling_partition_test.go
  pkg/scheduler/tests/scheduler_recovery_test.go
  pkg/scheduler/tests/scheduler_reservation_test.go
  pkg/scheduler/tests/scheduler_smoke_test.go
Labels: bug, build

#115 [YUNIKORN-61] Typo in user-guide.md sleep job example
  docs/user-guide.md
Labels: documentation

#114 [YUNIKORN-60] Not working link pointing to build document in deployment.md
  docs/setup/deployment.md
Labels: documentation
